version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:20.9.0
    steps:
      - checkout
      
      # Restore pnpm cache
      - restore_cache:
          key: pnpm-cache-{{ checksum "pnpm-lock.yaml" }}
          
      # Install pnpm globally
      - run:
          name: Install pnpm
          command: npm install -g pnpm

      # Install Dependencies using pnpm
      - run:
          name: Install Dependencies
          command: pnpm install

      # Cache the pnpm store
      - save_cache:
          key: pnpm-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store  # pnpm uses this directory for cached dependencies

      # Build the React App
      - run:
          name: Build React App
          command: pnpm run build

      # Cache the build output
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./build  # Adjust if your build directory is different

      # Deploy to Netlify
      - run:
          name: Deploy to Netlify
          command: npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=build

workflows:
  build-deploy:
    jobs:
      - build  # Removed filters to run for all branches
